#argocd application yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: users=146256358142.dkr.ecr.us-east-1.amazonaws.com/users:0.x
    argocd-image-updater.argoproj.io/users.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - argocd.argoproj.io/resources-finalizer
  name: users-dev
  namespace: argocd
spec:
  project: default
  source:
    helm:
      parameters:
        - name: image.repository
          value: 146256358142.dkr.ecr.us-east-1.amazonaws.com/users
        - name: service.port
          value: "8080"
        - name: livenessProbe.httpGet.path
          value: /healthz
        - name: readinessProbe.httpGet.path
          value: /healthz
        - name: image.tag
          value: 0.1.0
    path: helm-charts/users
    repoURL: git@github.com:kagodarog/k8s.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
